feat: show label when input no width AB#8568
Neovici/cosmoz-input pull request #45
Opened 2023-02-01 07:43 UTC by pawelkuriata

Added style for showing label based on attribute when the width of the input is 0 or close to 0, for cosmoz-autocomplete purposes.

2023-02-08 18:45 UTC, cristinecula commented
How will this look?

2023-02-10 08:10 UTC, pawelkuriata commented
It's for the autocomplete changes. When more items are selected the input field gets smaller and the label stops being visible
![image](https://user-images.githubusercontent.com/123149999/218036771-267d6836-b76a-4a16-aa1f-e51d400b79d8.png)

With this change the label will overflow over the selected items.
![image](https://user-images.githubusercontent.com/123149999/218037266-8bc69d9f-c54e-41a6-9fa2-6e539a947b03.png)

2023-02-13 15:12 UTC, cristinecula commented
But do we need a new attribute for this? Shouldn't this be the default behaviour?

2023-02-20 18:43 UTC, cristinecula requested changes
Adding an attribute depending on the available size seems very unwieldly. For example, the input is used in the headers of cosmoz-omnitable, which has resizable columns. Would cosmoz-omnitable have to add/remove the attribute based on the width of the column? Please figure out a different approach to implement this change.

2023-09-27 07:47 UTC, closed without merging